config/routes.rb
ExampleStartup::Application.routes.draw do
  resources :ads do
    collection do
      get 'my'
    end
  end

  resources :events do
    collection do
      get 'my'
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "home/index"

  root :to => 'home#index'

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  attr_accessible :contact, :description, :location, :title

  belongs_to :owner, :class_name => "User"

  validates :title, :presence => true
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :edit, :update, :delete, :my]

  def my
    @ads = current_user.adminable_ads
    render :index
  end

  # GET /ads
  # GET /ads.json
  def index
    @ads = Ad.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ads }
    end
  end

  # GET /ads/1
  # GET /ads/1.json
  def show
    @ad = Ad.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ad }
    end
  end

  # GET /ads/new
  # GET /ads/new.json
  def new
    @ad = Ad.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ad }
    end
  end

  # GET /ads/1/edit
  def edit
    @ad = current_user.adminable_ads.find(params[:id])
  end

  # POST /ads
  # POST /ads.json
  def create
    @ad = current_user.adminable_ads.new(params[:ad])

    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: 'Ad was successfully created.' }
        format.json { render json: @ad, status: :created, location: @ad }
      else
        format.html { render action: "new" }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ads/1
  # PUT /ads/1.json
  def update
    @ad = current_user.adminable_ads.find(params[:id])

    respond_to do |format|
      if @ad.update_attributes(params[:ad])
        format.html { redirect_to @ad, notice: 'Ad was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy
    @ad = current_user.adminable_ads.find(params[:id])
    @ad.destroy

    respond_to do |format|
      format.html { redirect_to ads_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/views/ads/_form.html.erb
<%= form_for @ad, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :contact, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :contact, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :location, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :location, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :owner_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :owner_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                ads_path, :class => 'btn' %>
  </div>
<% end %>

app/views/ads/edit.html.erb
<%- model_class = Ad -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ads/index.html.erb
<%- model_class = Ad -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:contact) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:owner_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @ads.each do |ad| %>
      <tr>
        <td><%= link_to ad.id, ad_path(ad) %></td>
        <td><%= ad.title %></td>
        <td><%= ad.description %></td>
        <td><%= ad.contact %></td>
        <td><%= ad.location %></td>
        <td><%= ad.owner_id %></td>
        <td><%=l ad.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_ad_path(ad), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      ad_path(ad),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Nowe ogłoszenie',
            new_ad_path,
            :class => 'btn btn-primary' %>

app/views/ads/new.html.erb
<%- model_class = Ad -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ads/show.html.erb
<%- model_class = Ad -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @ad.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @ad.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contact) %>:</strong></dt>
  <dd><%= @ad.contact %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= @ad.location %></dd>
  <dt><strong><%= model_class.human_attribute_name(:owner_id) %>:</strong></dt>
  <dd><%= @ad.owner_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              ads_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_ad_path(@ad), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              ad_path(@ad),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>