config/routes.rb
ExampleStartup::Application.routes.draw do
  resources :ads do
    collection do
      get 'my'
    end
  end

  resources :events do
    collection do
      get 'my'
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "home/index"

  root :to => 'home#index'

end

app/views/layouts/_common_head.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><%= content_for?(:title) ? yield(:title) : "Czwarty do Brydża" %></title>
<%= csrf_meta_tags %>

<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
<![endif]-->

<%= stylesheet_link_tag "application", :media => "all" %>

<!-- For third-generation iPad with high-resolution Retina display: -->
<!-- Size should be 144 x 144 pixels -->
<%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

<!-- For iPhone with high-resolution Retina display: -->
<!-- Size should be 114 x 114 pixels -->
<%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

<!-- For first- and second-generation iPad: -->
<!-- Size should be 72 x 72 pixels -->
<%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

<!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
<!-- Size should be 57 x 57 pixels -->
<%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

<!-- For all other devices -->
<!-- Size should be 32 x 32 pixels -->
<%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

app/views/layouts/_common_nav.html.erb
<!-- NAVBAR
     ================================================== -->
<div class="navbar-wrapper">
  <!-- Wrap the .navbar in .container to center it within the absolutely positioned parent. -->
  <div class="container">

    <div class="navbar navbar-inverse">
      <div class="navbar-inner">
        <!-- Responsive Navbar Part 1: Button for triggering responsive navbar (not covered in tutorial). Include responsive CSS to utilize. -->
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">Czwarty do brydża</a>
        <!-- Responsive Navbar Part 2: Place all navbar contents you want collapsed withing .navbar-collapse.collapse. -->
        <div class="nav-collapse collapse">
          <ul class="nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Ogłoszenia <b class="caret"></b></a>
              <ul class="dropdown-menu">
		<li><%= link_to 'Przejrzyj ogłoszenia', ads_path -%></li>
		<% if user_signed_in? -%>
		  <li><%= link_to 'Moje ogłoszenia', my_ads_path -%></li>
		<% end -%>
                <li class="divider"></li>
		<li><%= link_to 'Dodaj ogłoszenie', new_ad_path -%></li>
              </ul>
            </li>

	    <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Wydarzenia <b class="caret"></b></a>
              <ul class="dropdown-menu">
		<li><%= link_to 'Znajdź wydarzenie', events_path -%></li>
		<% if user_signed_in? -%>
		  <li><%= link_to 'Moje wydarzenia', my_events_path -%></li>
		<% end -%>
                <li class="divider"></li>
		<li><%= link_to 'Zorganizuj spotkanie', new_event_path -%></li>
              </ul>
            </li>
          </ul>
	  <% if user_signed_in? -%>
	    <ul class='nav pull-right'>
	      <li class='divider-vertical'></li>
	      <li class='dropdown'>
		<a href="#" class="dropdown-toggle" data-toggle="dropdown" id="menu-settings"><i class='icon-white icon-cog'></i>
		  <b class='caret'></b>
		</a>
		<ul class='dropdown-menu'>
		  <li><%= link_to 'Ustawienia konta', edit_user_registration_path %></li>
		</ul>
	      </li>
	      <li class='divider-vertical'></li>
	      <li>
		<%= link_to(destroy_user_session_path, :method=>'delete') do %>
		  <i class='icon-white icon-off'></i>
		<% end -%>
	      </li>
	    </ul>
	  <% end -%>
	  
        </div><!--/.nav-collapse -->
      </div><!-- /.navbar-inner -->
    </div><!-- /.navbar -->

  </div> <!-- /.container -->
</div><!-- /.navbar-wrapper -->

app/views/layouts/_homepage_carousel.html.erb
<!-- Carousel
     ================================================== -->
<div id="myCarousel" class="carousel slide">
  <div class="carousel-inner">
    <div class="item">
      <%= image_tag 'slide-01.jpg' -%>
      <div class="container">
        <div class="carousel-caption">
          <h1>Chcę zagrać w Brydża!</h1>
          <p class="lead">Zaproś znajomych na partyjkę, lub znajdź nowych brydżowych kolegów w Twojej okolicy.</p>
        </div>
      </div>
    </div>
    <div class="item active">
      <%= image_tag 'slide-02.jpg' -%>
      <div class="container">
        <div class="carousel-caption">
          <h1>Szukam partnera!</h1>
          <p class="lead">Jesteś singlem? Przejrzyj ogłoszenia innych brydżystów lub dodaj własne. Znajdź swoją drugą połówkę, chodźby na jedną rozgrywkę ;). </p>
        </div>
      </div>
    </div>
    <div class="item">
      <%= image_tag 'slide-03.jpg' -%>      
      <div class="container">
        <div class="carousel-caption">
          <h1>Mogę być nawet Dziadkiem!</h1>
          <p class="lead">Szukasz okazji do gry? Przejrzyj ogłoszenia o brydżowych imprezach w okolicy, lub zorganizuj swoje. </p>
        </div>
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="/#myCarousel" data-slide="prev">‹</a>
  <a class="right carousel-control" href="/#myCarousel" data-slide="next">›</a>
</div><!-- /.carousel -->

app/views/layouts/_homepage_marketing.html.erb
<div class="container marketing">
  
  <div class="row">
    <div class="span4">
      <img class="img-circle" data-src="holder.js/140x140">
      <h2>Szukasz Partnera?</h2>
      <p>Szukasz partnera do brydża? Przejrzyj ogłoszenia innych brydżystów lub zamieść swoje.</p>
      <p><%= link_to 'Przejrzyj ogłoszenia »', ads_path, class: "btn btn-large btn-block btn-success" -%></p>
      <p><%= link_to 'Dodaj ogłoszenie »', new_ad_path, class: "btn btn-large btn-block" -%></p>
    </div>
    <div class="span4">
      <img class="img-circle" data-src="holder.js/140x140">
      <h2>Chcesz Zagrać?</h2>
      <p>Poszukaj okazji do zagrania w Twojej okolicy, lub zaproponuj własne wydarzenie. </p>
      <p><%= link_to 'Znajdź wydarzenie »', events_path, class: "btn btn-large btn-block btn-success" -%></p>
      <p><%= link_to 'Zorganizuj spotkanie »', new_event_path, class: "btn btn-large btn-block" -%></p>
    </div>
  </div>

  <hr class="featurette-divider">

  <footer>
    <p>&copy; Czwarty do Brydża 2013</p>
  </footer>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= render :partial => '/layouts/common_head' -%>
  </head>
  <body>

    <%= render :partial => '/layouts/common_nav' -%>
	
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>

      <footer>
        <p>&copy; Czwarty do Brydża 2013</p>
      </footer>

    </div>

    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/homepage.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= render :partial => '/layouts/common_head' -%>
    <%= stylesheet_link_tag "homepage", :media => "all" %>
  </head>
  <body screen_capture_injected="true">


    <%= render :partial => '/layouts/common_nav' -%>

    <%= render :partial => '/layouts/homepage_carousel' -%>

    <%= render :partial => '/layouts/homepage_marketing' -%>
    
    <%= javascript_include_tag "application" %>
    
    <script>
      !function ($) {
        $(function(){
          // carousel demo
          $('#myCarousel').carousel()
        })
      }(window.jQuery)
    </script>
  </body>
</html>